import 'package:get/get.dart';

class Mytranlaztion extends Translations{
  @override
  Map<String, Map<String, String>> get keys =>{
    "ar":{
      "1":"ابحث عن حجزك",
      "2":"نساعدك علئ البحث ضمن مواعيد حجز عدد كبير من شركات النقل بضغطه زر",
      "3":"الحجز او لاين",
      "4":"نساعدك علئ حجز رحلات بشكل اسرع دون تكبد عناء الذهاب الئ محطات النقل",
      "5":"الحجز او لاين",
      "6":"نساعدك علئ حجز رحلات بشكل اسرع دون تكبد عناء الذهاب الئ محطات النقل",
      "7":" تسجيل الدخول",
      "8":"الجوال",
      "9":"البريد الإلكتروني",
      "10":"كلمة المرور",
      "11":"هل نسيت كلمة المرور؟",
      "12":"دخول",
      "13":"الدخول كزائر",
      "14":"ليس لديك حساب؟",
      "15":"أنشئ حسابا",
      "16":"الرجاء إدخال البريد الإلكتروني",
      "17":"صيغة البريد الإلكتروني غير صحيحة",
      "18":"الرجاء إدخال كلمة المرور",
      "19":"الرجاء إدخال رقم الهاتف",
      "20":"فشل تسجيل الدخول",
      "21":"بيانات الاعتماد غير صحيحة. الرجاء المحاولة مرة أخرى.",
      "22":"يجب ادخال اسم المستخدم",
      "23":"رقم الجوال مطلوب",
      "24":"البريد الإلكتروني مطلوب",
      "25":"كلمة المرور لا تقل عن 6 أحرفب",
      "26":"كلمتا المرور غير متطابقتين",
      "27":"ذكر",
      "28":"أنثئ",
      "29":"إنشاء حساب",
      "30":"الاسم الكامل",
      "31":"الجنس",
      "32":"تأكيد كلمة المرور",
      "33":"نسيت كلمه المرور",
      "34":'أدخل بريدك المسجل لاستقبال كود استعادة كلمة المرور',
      "35":"تعليمات إعاده تعيين كلمه المرور",
      "36":" إنشاء كلمه المرور الجديده",
      "37":"يجب أن تكون كلمه المرور الجديده الخاصه بك مختلفه عن كلمه المرور المستخدمه سابقا ",
      "38":"موافق",
      "39":"ارسال",
      "40":"الرئيسية",
      "41":"حجوزاتي",
      "42":"المسافرين",
      "43":"الإعدادات",
      "44":"الأشعارات",
      "45":"الكل",
      "46":"الحجوزات",
      "47":"العروض",
      "48":"التحديثات",
      "49":"رقم الجوال ",
      "50":"البحث ",
      "51":"التحقق من الايميل ",
      "52":"بحث",
      "53":"رجوع",
      "54":"إلى",
      "55":"الانطلاق",
      "56":"نوع الرحلة",
      "57":"نوع الرحلة",
      "58":"تفاصيل الرحلة",
      "59":"التاريخ",
      "60":"نتائج البحث",
      "61":"فلترة الرحلات",
      "62":"حجز الرحلة",
      "63":" متابعه",
      "64":"جاري الإرسال...",
      "65":"كلمة المرور الجديدة",
      "66":"التحقق من الكود",
      "67":"رمز التحقق",
      "68":"أدخل الكود المرسل لبريدك الإلكتروني لاستعادة كلمة المرور",
      "69":"إعدادات الإشعارات",
      "70":"تفضيلات الإشعارات",
      "71":"اختر أنواع الإشعارات التي ترغب في استلامها",
      "72":"تحديثات الحجز",
      "73":"إشعارات عن حالة حجوزاتك",
      "74":"العروض الخاصة",
      "75":"احصل على أحدث العروض والخصومات",
      "76":"إشعارات البريد الإلكتروني",
      "77":"تلقي الإشعارات عبر البريد",
      "78":"إشعارات الرسائل النصية",
      "79":"تلقي الإشعارات عبر SMS",
      "80":"الإشعارات الفورية",
      "81":"إشعارات على الهاتف",
      "82":"الدعم والمساعدة",
      "83":"كيف يمكننا مساعدتك؟",
      "84":"نحن هنا لمساعدتك في أي وقت",
      "85":"تقديم تذكرة دعم جديدة",
      "86":"اتصال هاتفي",
      "87":"اتصل الآن",
      "88":"بريد إلكتروني",
      "89":"أرسل رسالة",
      "90":"دردشة مباشرة",
      "91":"متاح على مدار الساعة",
      "92":"ابدأ المحادثة",
      "93":"زائر",
      "94":"لا يوجد بريد إلكتروني",
      "95":"الأسئلة الشائعة",
      "96":"أجوبة جاهزة وسريعة",
      "97":"تسجيل الخروج",
      "98":"تسجيل خروج آمن",
      "99":"إجراءات سريعة",
      "100":"مركز المساعدة",
      "101":"اللغة",
      "102":"تغيير لغة التطبيق",
      "103":"تواصل مع فريقنا",
      "104":"عن التطبيق",
      "105":"تعرف علينا أكثر",
      "106":"سياسات",
      "107":"عرض سياسات كل شركه",
      "108":"لمعرفه تفاصيل بشكل الي",
      "109":"اقتراح",
      "110":"تقديم اقتراحات حسب تفضيلاتك",
      "111":"معرفه جميع الاسئله التي تبحث عنها",
      "112":"اختر اللغة",
      "113":"شركائنا",
      "114":"خدمات اخرئ",
      "115":"تذكرة دعم جديدة",
      "116":"نوع المشكلة",
      "117":"اختر نوع المشكلة",
      "118":"عنوان التذكرة",
      "119":"الرجاء اختيار نوع المشكلة",
      "120":"وصف مختصر للمشكلة",
      "121":"تفاصيل المشكلة",
      "122":"اشرح المشكلة بالتفصيل...",
      "123":"إلغاء",
      "124":"إرسال التذكرة",
      "125":"تغيير المقاعد",
      "126":"إشعارات عند توفر مقاعد أفضل",
      "127":"عروض حصرية",
      "128":"اكتشف أفضل الخصومات والرحلات الجديدة",
      "129":"إشعارات الهاتف (Push)",
      "130":"استلام تنبيهات فورية داخل التطبيق",
      "131":"رسائل نصية (SMS)",
      "132":"تنبيهات عبر رقم هاتفك المسجل",
























    },
    "en":{
      "1":"Find your reservation",
      "2":"We help you search within the times of booking a large number of \n transportation companies with the click of abutton",
      "3":"Book online",
      "4":"We help you to book flights faster,without the trouble\n of going to the transporation stations",
      "5":"Book online",
      "6":"We help you to book flights faster,without the trouble\n of going to the transporation stations",
      "7":"Login",
      "8":"Phone ",
      "9":"Email",
      "10":"Password",
      "11":"Did you forget the password?",
      "12":"Login",
      "13":"Entry as visitor",
      "14":"You don`t have an account?",
      "15":"Create an account",
      "16":"Please enter the email",
      "17":"The e-mail format is correct",
      "18":"Please enter your password",
      "19":"Please enter your phone",
      "20":"Login Failed",
      "21":"The credentials are incorrect,please try again",
      "22":"You must enter the username",
      "23":"The phone number is required ",
      "24":"Email is required",
      "25":"The password is not less than 6 letters",
      "26":"The tow password are not identical",
      "27":"Mael",
      "28":"Female",
      "29":"Create account",
      "30":"Fual name",
      "31":"Sex",
      "32":"Confirm the password",
      "33":"Forget your password",
      "34":"Enter your registered email below to receive a code to reset your password",
      "35":"password reset instuction",
      "36":"Creat new password",
      "37":"Your new password must be differenet from \n previously used passwords",
      "38":"Ok",
      "39":"Send",
      "40":"Home",
      "41":"Reservation",
      "42":"Travlers",
      "43":"Setting",
      "44":"Notifications",
      "45":"All",
      "46":"Reservation",
      "47":"Offers",
      "48":"Updates",
      "49":"Phone number",
      "50":"Sherch",
      "51":"Check of E-mail",
      "52":"Sherch",
      "53":"Back",
      "54":"to",
      "55":"departure",
      "56":"Typr of trip",
      "57":"Destination information",
      "58":"Trip deatils",
      "59":"Hestory",
      "60":"Tarust Sherch",
      "61":"Flitter Trips",
      "62":"Booking Trip",
      "63":"Follow",
      "64":"Sending ...",
      "65":"New password",
      "66":"Check code",
      "67":"Code",
      "68":"Enter the code sent to your email to recover your password",
      "69":"Notification settings",
      "70":"Notification preferences",
      "71":"Select the types of notifications you want to receive",
      "72":"Reservation updates",
      "73":"Notifications about the status of your reservations",
      "74":"Special offers",
      "75":"Get the latest offers and discounts",
      "76":"Email notifications",
      "77":"Receive notifications by email",
      "78":"SMS notifications",
      "79":"Receive notifications by SMS",
      "80":"Immediate notifications",
      "81":"Phone notifications",
      "82":"Support and help",
      "83":"How can we help you?",
      "84":"We are here to help you at any time",
      "85":"Submit a new support ticket",
      "86":"Call me",
      "87":"Call now",
      "88":"Email",
      "89":"Send message",
      "90":"Live chat",
      "91":"Available 24/7",
      "92":"Start a conversation",
      "93":"Visitor",
      "94":"No email",
      "95":"Frequently asked questions",
      "96":"Ready answers",
      "97":"Log out",
      "98":"Log out safe",
      "99":"Quick actions",
      "100":"Help center",
      "101":"Language",
      "102":"Change the language of the application",
      "103":"Support and help",
      "104":"About us",
      "105":"Terms and conditions",
      "106":"Privacy policy",
      "107":"View privacy policies of all companies",
      "108":"To learn more details automatically",
      "109":"Suggestions",
      "110":"Provided suggestions based on your preferences",
      "111":"Find answers to all the questions you are looking for",
      "112":"Choose a language",
      "113":"Our partners",
      "114":"Other services",
      "115":"New support ticket",
      "116":"Type of problem",
      "117":"Choose a type of problem",
      "118":"Problem title",
      "119":"Please select the type of problem",
      "120":"Describe the problem",
      "121":" Problem description",
      "122":"Explain the problem in detail",
      "123":"Cancel",
      "124":"Send ticket",
      "125":"Seat changes",
      "126":"Notifications when better seats are available",
      "127":"Exclusive offers",
      "128":"Discover the best discounts and new trips",
      "129":"Push Notifications",
      "130":"Receive instant in-app alerts",
      "131":"SMS Messages",
      "132":"Alerts via your registered phone number",






    }
  };

}