-- Create a table for contact messages
create table public.contact_messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  name text not null,
  email text not null,
  subject text not null,
  message text not null,
  status text default 'new' check (status in ('new', 'read', 'replied', 'archived')),
  ip_address text,
  user_id uuid references auth.users(id) -- Optional link to registered user if logged in
);

-- Enable RLS
alter table public.contact_messages enable row level security;

-- Allow anyone (anon) to insert messages (for public contact form)
create policy "Anyone can insert contact messages"
  on public.contact_messages for insert
  with check (true);

-- Allow admins/support to view messages (assuming admin role or similar, mostly for future dashboard use)
-- For now, we will just allow authenticated users to view their own if we link them,
-- or just keep it restricted. Let's create a policy for admins if you have roles set up,
-- otherwise, just basic insert for public is the critical part for the form to work.

-- Let's stick to the requirement: "Contact form works".
-- We need INSERT permission for 'anon' and 'authenticated' roles.

grant insert on public.contact_messages to anon, authenticated;
grant select on public.contact_messages to service_role;
