-- Create partner_invoices table if not exists
CREATE TABLE IF NOT EXISTS public.partner_invoices (
    invoice_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    partner_id BIGINT REFERENCES public.partners(partner_id) ON DELETE CASCADE,
    invoice_number TEXT NOT NULL UNIQUE,
    period_start DATE NOT NULL,
    period_end DATE NOT NULL,
    total_amount DECIMAL(10, 2) NOT NULL DEFAULT 0,
    platform_commission DECIMAL(10, 2) NOT NULL DEFAULT 0,
    partner_net DECIMAL(10, 2) NOT NULL DEFAULT 0,
    status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'paid', 'cancelled')),
    due_date DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.partner_invoices ENABLE ROW LEVEL SECURITY;

-- Policies

-- 1. Superuser can do everything
CREATE POLICY "Superusers can manage invoices"
ON public.partner_invoices
FOR ALL
USING (
    EXISTS (
        SELECT 1 FROM public.user_roles ur
        WHERE ur.auth_id = auth.uid()
        AND ur.role = 'SUPERUSER'
    )
);

-- 2. Partners can VIEW their own invoices
CREATE POLICY "Partners can view own invoices"
ON public.partner_invoices
FOR SELECT
USING (
    partner_id = (
        SELECT partner_id FROM public.user_roles
        WHERE auth_id = auth.uid()
        LIMIT 1
    )
);

-- Add indexes
CREATE INDEX IF NOT EXISTS idx_partner_invoices_partner_id ON public.partner_invoices(partner_id);
CREATE INDEX IF NOT EXISTS idx_partner_invoices_status ON public.partner_invoices(status);
