-- ========================================================
-- PERMISSIONS SCHEMA & SEEDING (Granular RBAC)
-- ========================================================

BEGIN;

-- 1. Drop existing tables to ensure schema consistency (Fixes "column does not exist" error)
DROP TABLE IF EXISTS public.role_permissions CASCADE;
DROP TABLE IF EXISTS public.permissions CASCADE;

-- 2. Create Permissions Table (The Catalog)
CREATE TABLE public.permissions (
    permission_code TEXT PRIMARY KEY, -- e.g. 'trips.view', 'trips.create'
    description TEXT NOT NULL,
    category TEXT NOT NULL, -- 'trips', 'bookings', 'fleet', 'financial', etc.
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Create Role Permissions Table (The Matrix)
CREATE TABLE public.role_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role TEXT NOT NULL, -- Changed from app_role to TEXT to support 'manager', 'accountant', etc.
    permission_code TEXT REFERENCES public.permissions(permission_code) ON DELETE CASCADE,
    partner_id INTEGER REFERENCES public.partners(partner_id) ON DELETE CASCADE, -- NULL = System Default
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(role, permission_code, partner_id) -- Prevent duplicates
);

-- 3. Enable RLS
ALTER TABLE public.permissions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.role_permissions ENABLE ROW LEVEL SECURITY;

-- 4. RLS Policies
-- Permissions Catalog: Readable by everyone authenticated (to show in UI)
CREATE POLICY "Authenticated can view permissions" ON public.permissions
    FOR SELECT TO authenticated USING (true);

-- Role Permissions:
-- Partners can view their own + system defaults
CREATE POLICY "Partners can view own role permissions" ON public.role_permissions
    FOR SELECT TO authenticated
    USING (
        partner_id = public.get_current_partner_id() 
        OR partner_id IS NULL
        OR public.has_role(auth.uid(), 'admin')
    );

-- Partners can manage ONLY their own custom permissions
CREATE POLICY "Partners can manage own role permissions" ON public.role_permissions
    FOR ALL TO authenticated
    USING (partner_id = public.get_current_partner_id())
    WITH CHECK (partner_id = public.get_current_partner_id());

-- Admins can manage everything
CREATE POLICY "Admins can manage all role permissions" ON public.role_permissions
    FOR ALL TO authenticated
    USING (public.has_role(auth.uid(), 'admin'));


-- 5. SEED DATA: Granular Permissions
INSERT INTO public.permissions (permission_code, category, description) VALUES
-- TRIPS
('trips.view', 'الرحلات', 'عرض قائمة الرحلات وتفاصيلها'),
('trips.create', 'الرحلات', 'إضافة رحلات جديدة وجدولتها'),
('trips.edit', 'الرحلات', 'تعديل تفاصيل الرحلات الحالية'),
('trips.delete', 'الرحلات', 'حذف الرحلات أو إلغاؤها'),
('trips.approve', 'الرحلات', 'الموافقة على الرحلات (للمشرفين)'),

-- BOOKINGS
('bookings.view', 'الحجوزات', 'عرض الحجوزات والبحث فيها'),
('bookings.create', 'الحجوزات', 'إنشاء حجز جديد للعملاء'),
('bookings.edit', 'الحجوزات', 'تعديل بيانات الحجز أو المقاعد'),
('bookings.cancel', 'الحجوزات', 'إلغاء الحجوزات'),
('bookings.refund', 'الحجوزات', 'معالجة استرداد الأموال'),

-- FLEET (Buses & Drivers)
('fleet.view', 'الأسطول', 'عرض قائمة الحافلات والسائقين'),
('fleet.manage', 'الأسطول', 'إضافة وتعديل وحذف الحافلات والسائقين'),
('fleet.maintenance', 'الأسطول', 'إدارة سجلات الصيانة'),

-- ROUTES
('routes.view', 'المسارات', 'عرض المسارات والمدن'),
('routes.manage', 'المسارات', 'إضافة وتعديل المسارات والأسعار'),

-- FINANCIAL
('financial.view', 'المالية', 'عرض التقارير المالية والإيرادات'),
('financial.export', 'المالية', 'تصدير التقارير المالية'),

-- USERS / EMPLOYEES
('users.view', 'المستخدمين', 'عرض قائمة الموظفين'),
('users.manage', 'المستخدمين', 'إضافة وتعديل وحذف الموظفين'),

-- SETTINGS
('settings.view', 'الإعدادات', 'عرض إعدادات الشركة'),
('settings.edit', 'الإعدادات', 'تعديل إعدادات الشركة وسياسات الإلغاء')

ON CONFLICT (permission_code) DO UPDATE 
SET description = EXCLUDED.description, category = EXCLUDED.category;


-- 6. SEED DATA: Default Role Assignments
-- We will define "System Defaults" (partner_id IS NULL) for common roles.

-- MANAGER (Full Access)
INSERT INTO public.role_permissions (role, permission_code, partner_id)
SELECT 'manager', permission_code, NULL FROM public.permissions
ON CONFLICT DO NOTHING;

-- ACCOUNTANT (Financials + View Access)
INSERT INTO public.role_permissions (role, permission_code, partner_id)
VALUES 
('accountant', 'financial.view', NULL),
('accountant', 'financial.export', NULL),
('accountant', 'bookings.view', NULL),
('accountant', 'bookings.refund', NULL),
('accountant', 'trips.view', NULL)
ON CONFLICT DO NOTHING;

-- DRIVER (View Trips Only - usually via mobile app, but good to have)
INSERT INTO public.role_permissions (role, permission_code, partner_id)
VALUES 
('driver', 'trips.view', NULL)
ON CONFLICT DO NOTHING;

-- SUPPORT (Bookings + View Trips)
INSERT INTO public.role_permissions (role, permission_code, partner_id)
VALUES 
('support', 'bookings.view', NULL),
('support', 'bookings.create', NULL),
('support', 'bookings.edit', NULL),
('support', 'bookings.cancel', NULL),
('support', 'trips.view', NULL),
('support', 'routes.view', NULL)
ON CONFLICT DO NOTHING;

-- SUPERVISOR (Trips + Fleet + Users)
INSERT INTO public.role_permissions (role, permission_code, partner_id)
VALUES 
('supervisor', 'trips.view', NULL),
('supervisor', 'trips.create', NULL),
('supervisor', 'trips.edit', NULL),
('supervisor', 'trips.approve', NULL),
('supervisor', 'fleet.view', NULL),
('supervisor', 'fleet.manage', NULL),
('supervisor', 'fleet.maintenance', NULL),
('supervisor', 'users.view', NULL),
('supervisor', 'users.manage', NULL)
ON CONFLICT DO NOTHING;

COMMIT;
