// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
    flowType: 'pkce',
  },
  global: {
    headers: {
      'x-client-info': 'ahjazly-web-app',
    },
  },
});

// Monitor auth state changes for better session management
supabase.auth.onAuthStateChange((event, session) => {
  console.log('[Supabase] Auth event:', event);

  if (event === 'SIGNED_OUT') {
    // Clear all auth-related storage
    try {
      localStorage.removeItem('supabase.auth.token');
      sessionStorage.clear();
      console.log('[Supabase] Cleared storage on sign out');
    } catch (error) {
      console.error('[Supabase] Error clearing storage:', error);
    }
  }

  if (event === 'TOKEN_REFRESHED') {
    console.log('[Supabase] Token refreshed successfully');
  }

  if (event === 'SIGNED_IN') {
    console.log('[Supabase] User signed in successfully');
  }
});
