-- Enable RLS on all new tables
-- Create UI Components Table
CREATE TABLE IF NOT EXISTS public.ui_components (
    component_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    component_type TEXT NOT NULL,
    component_name TEXT NOT NULL,
    title TEXT,
    subtitle TEXT,
    content TEXT,
    image_url TEXT,
    background_image TEXT,
    link_url TEXT,
    link_text TEXT,
    button_text TEXT,
    button_url TEXT,
    button_style TEXT,
    custom_styles JSONB DEFAULT '{}'::jsonb,
    custom_data JSONB DEFAULT '{}'::jsonb,
    status TEXT DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'scheduled', 'archived')),
    start_date TIMESTAMPTZ,
    end_date TIMESTAMPTZ,
    priority INTEGER DEFAULT 0,
    click_count INTEGER DEFAULT 0,
    view_count INTEGER DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Page Layouts Table
CREATE TABLE IF NOT EXISTS public.ui_page_layouts (
    layout_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    page_key TEXT NOT NULL UNIQUE,
    page_title TEXT NOT NULL,
    page_description TEXT,
    meta_title TEXT,
    meta_description TEXT,
    is_active BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Component Placements Table (Many-to-Many Link)
CREATE TABLE IF NOT EXISTS public.ui_component_placements (
    placement_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    layout_id BIGINT REFERENCES public.ui_page_layouts(layout_id) ON DELETE CASCADE,
    component_id BIGINT REFERENCES public.ui_components(component_id) ON DELETE CASCADE,
    position TEXT DEFAULT 'main',
    display_order INTEGER DEFAULT 0,
    is_visible BOOLEAN DEFAULT true,
    custom_config JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Advertisements Table
CREATE TABLE IF NOT EXISTS public.ui_advertisements (
    ad_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ad_name TEXT NOT NULL,
    ad_type TEXT NOT NULL, -- banner, sidebar, popup
    ad_position TEXT,
    target_pages TEXT[] DEFAULT '{all}',
    image_url TEXT,
    mobile_image_url TEXT,
    link_url TEXT,
    alt_text TEXT,
    advertiser_name TEXT,
    start_date TIMESTAMPTZ,
    end_date TIMESTAMPTZ,
    is_active BOOLEAN DEFAULT true,
    priority INTEGER DEFAULT 0,
    click_count INTEGER DEFAULT 0,
    impression_count INTEGER DEFAULT 0,
    daily_budget NUMERIC,
    total_budget NUMERIC,
    cost_per_click NUMERIC,
    cost_per_impression NUMERIC,
    target_audience JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Promotions Table
CREATE TABLE IF NOT EXISTS public.ui_promotions (
    promo_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    promo_code TEXT UNIQUE,
    promo_name TEXT NOT NULL,
    promo_type TEXT NOT NULL, -- discount, cashback, bogo
    discount_value NUMERIC,
    min_booking_amount NUMERIC DEFAULT 0,
    max_discount NUMERIC,
    applicable_routes BIGINT[],
    applicable_partners BIGINT[],
    usage_limit INTEGER,
    usage_count INTEGER DEFAULT 0,
    per_user_limit INTEGER DEFAULT 1,
    start_date TIMESTAMPTZ DEFAULT NOW(),
    end_date TIMESTAMPTZ,
    is_active BOOLEAN DEFAULT true,
    banner_image TEXT,
    display_on_home BOOLEAN DEFAULT false,
    terms_conditions TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Create Site Settings Table
CREATE TABLE IF NOT EXISTS public.ui_site_settings (
    setting_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    setting_key TEXT UNIQUE NOT NULL,
    setting_value TEXT,
    setting_type TEXT DEFAULT 'string',
    setting_group TEXT DEFAULT 'general',
    description TEXT,
    is_public BOOLEAN DEFAULT false,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE public.ui_components ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ui_page_layouts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ui_component_placements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ui_advertisements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ui_promotions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ui_site_settings ENABLE ROW LEVEL SECURITY;

-- RLS Policies

-- 1. Components: Admins full access, Public read published only
CREATE POLICY "Admins full access components" ON public.ui_components
    FOR ALL TO authenticated
    USING (public.has_role(auth.uid(), 'admin'))
    WITH CHECK (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Public read published components" ON public.ui_components
    FOR SELECT TO anon, authenticated
    USING (status = 'published');

-- 2. Layouts: Admins full access, Public read active only
CREATE POLICY "Admins full access layouts" ON public.ui_page_layouts
    FOR ALL TO authenticated
    USING (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Public read active layouts" ON public.ui_page_layouts
    FOR SELECT TO anon, authenticated
    USING (is_active = true);

-- 3. Placements: Admins full access, Public read visible only
CREATE POLICY "Admins full access placements" ON public.ui_component_placements
    FOR ALL TO authenticated
    USING (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Public read visible placements" ON public.ui_component_placements
    FOR SELECT TO anon, authenticated
    USING (is_visible = true);

-- 4. Advertisements: Admins full access, Public read active only
CREATE POLICY "Admins full access ads" ON public.ui_advertisements
    FOR ALL TO authenticated
    USING (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Public read active ads" ON public.ui_advertisements
    FOR SELECT TO anon, authenticated
    USING (is_active = true AND (start_date IS NULL OR start_date <= NOW()) AND (end_date IS NULL OR end_date >= NOW()));

-- 5. Promotions: Admins full access, Public read active only
CREATE POLICY "Admins full access promotions" ON public.ui_promotions
    FOR ALL TO authenticated
    USING (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Public read active promotions" ON public.ui_promotions
    FOR SELECT TO anon, authenticated
    USING (is_active = true);

-- 6. Site Settings: Admins full access, Public read is_public only
CREATE POLICY "Admins full access settings" ON public.ui_site_settings
    FOR ALL TO authenticated
    USING (public.has_role(auth.uid(), 'admin'));

CREATE POLICY "Public read public settings" ON public.ui_site_settings
    FOR SELECT TO anon, authenticated
    USING (is_public = true);

-- Seed Initial Data (Optional)
INSERT INTO public.ui_page_layouts (page_key, page_title, page_description)
VALUES 
('home', 'الرئيسية', 'الصفحة الرئيسية للموقع'),
('search', 'نتائج البحث', 'صفحة عرض الرحلات المتاحة'),
('booking', 'الحجز', 'صفحة إتمام الحجز'),
('about', 'من نحن', 'معلومات عن الشركة'),
('contact', 'اتصل بنا', 'صفحة التواصل')
ON CONFLICT (page_key) DO NOTHING;

INSERT INTO public.ui_site_settings (setting_key, setting_value, setting_type, setting_group, description, is_public)
VALUES
('site_name', 'Ahjazly', 'string', 'general', 'اسم الموقع', true),
('site_logo', '/logo.png', 'image', 'general', 'شعار الموقع', true),
('footer_text', 'جميع الحقوق محفوظة © 2025', 'string', 'footer', 'نص الفوتر', true),
('contact_email', 'support@ahjazly.com', 'string', 'contact', 'بريد الدعم', true)
ON CONFLICT (setting_key) DO NOTHING;
